Add controllers Sprint 13
Jon7even/java-shareit pull request #1
Opened 2023-07-01 13:52 UTC by Jon7even

Надеюсь, что правильно понял структуру)

2023-07-01 21:37 UTC, andrew-larkin requested changes
Привет! Очень хороший старт, молодец что написал юнит-тесты для контроллеров - это правильный подход. По коду требуются небольшие изменения для улучшения архитектуры и наибольшей приближенности к реальным проектам. Если внедрим все описанные в комментах вещи, то это приложение через 3 ближайших спринта ничем не будет отличаться от микросервиса, который создается в том же Яндексе или Авито. По сути, после завершения этого проекта можно смело искать работу)

2023-07-01 21:37 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemResponseDTO createItem(@RequestHeader("X-Sharer-User-Id") Optional<Long> userId,
Давай для этого приложения добавим новый класс-обертку для методов контроллера ResponseEntity - он возвращает не только json, но и http-статус, что довольно удобно. Будет выглядеть как-то так:
return ResponseEntity.ok().body(itemService.createItem(itemDto, userId));
Для всех методов во всех контроллерах стоит его добавить

2023-07-01 21:37 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/ItemResponseDTO.java
> +    private long id;
в dto лучше использовать врапперы (int -> Integer) вместо примитивов, чтобы не нарваться на NPE при отсутствующих параметрах в запросе

2023-07-01 21:37 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/mapper/MapperItemDTO.java
> +public final class MapperItemDTO {
для этого приложения также давай добавим библиотеку mapStruct - она используется на всех реальных проектах, будет очень полезно ее изучить. Благодаря ней методы маппера можно будеть написать в одну строчку

2023-07-01 21:37 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Item createItem(ItemCreateInServiceDTO itemCreateInServiceDTO);
непосредственный маппинг из entity в dto лучше производить внутри сервиса. Таким образом контроллеры будут легковесными и будут выполнять единственную функцию - служить маршрутизатором запросов (принцип S в аббреавиатуре SOLID). Т.е. возвращаемый тип методов сервиса - dto, а не entity

2023-07-01 21:37 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceIml.java
> +    private final UserService userService;
внедрение сервиса в другой сервис (в случае если оба общаются с БД) - не лучшая практика, т.к. из-за этого может нарушиться транзакционность. Выходом из такой ситуации будет внедрение не сервиса, а репозитория - тогда проблема с транзакционностью пропадает

2023-07-01 21:37 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#spring.config.activate.on-profile=ci,test
это добавится чуть позже, пока что можно удалить

2023-07-02 09:05 UTC, Jon7even commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +    public ItemResponseDTO createItem(@RequestHeader("X-Sharer-User-Id") Optional<Long> userId,
Попробую сделать! Я на прошлом ТЗ хотел его реализовать, но наткнулся на [статью на хабре](https://habr.com/ru/articles/675716/), где советовали все-таки делать без него и от туда взял  @ResponseStatus(HttpStatus.CREATED) и другие идеи (из комментов в том числе)

2023-07-02 09:10 UTC, Jon7even commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Item createItem(ItemCreateInServiceDTO itemCreateInServiceDTO);
Спасибо! Разобрался с первым S))

2023-07-02 09:11 UTC, Jon7even commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceIml.java
> +    private final UserService userService;
Долго продумывал этот момент, сначала даже подключил репозиторий, но потом когда понял, что дублирую код, мысли были такие -> в сервисе уже вся обработка реализована. Спасибо, понял, что так не надо))

2023-07-06 10:09 UTC, merged