Add item requests Sprint15
Jon7even/java-shareit pull request #3
Opened 2023-08-02 14:55 UTC by Jon7even

Нет слов одни эмоции:)

2023-08-07 16:28 UTC, andrew-larkin requested changes
Привет! Новый функционал реализован очень качественно, не было обнаружено никаких серьезных проблем. Тесты написано просто шикарно, покрытие и их качество отличное. Есть пара поих комментариев, но они могут рассматриваться как рекомендации.

2023-08-07 16:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestListTO.java
> +    private Optional<Long> idUser;
тоже вместо Optional можно тут везде применить @NotNull, с ним скорее всего будет удобнее

2023-08-07 16:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        List<ItemResponseBookingAndCommentTO> getAllItemsByUserId = itemService.getAllItemsByUserId(
можно не создавать переменную - сразу вставить результат в .body()

2023-08-07 16:28 UTC, andrew-larkin commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreateTO.java
> +public class CommentCreateTO {
названия ты имел ввиду, наверное, DTO

2023-08-08 10:37 UTC, Jon7even commented on src/main/java/ru/practicum/shareit/item/dto/CommentCreateTO.java
> +public class CommentCreateTO {
Нет, именно TO. Еще на начале спринта решил заморочиться и у меня возникли сомнения по поводу длинных названий, и их регистра, типа "DTO" или все-таки "Dto" и выяснил по внятным комментариям (это был не один комментарий и не с одного источника), что лучше всего вообще не именовать окончание, т.к. из контекста понятно, что это класс DTO, но мне как и другим такое не понравилось, проще понимать dto класс, когда ты увидел название, это быстрей, ИМХО. Так вот, увидел такую рекомендацию именовать окончанием TO, т.е. Transfer Object, мне это показалось логичным :)

2023-08-10 09:49 UTC, merged